### ISSUE TITLE
Mouse cursor over items

### ISSUE THREAD

**Issue by yrashk** [Frezyx/sidebarx#16]
**Is your feature request related to a problem? Please describe.**
When hovering over items, the mouse cursor doesn't change. This gives a wrong indication to users.

**Describe the solution you'd like**
Upon hovering a clickable item, the mouse cursor should become a pointer.

**Describe alternatives you've considered**
I haven't considered any

**Additional context**

**Comment by Frezyx** [comment]
Hello @yrashk !
Good point !

I implement this functionality in new [PR](https://github.com/Frezyx/sidebarx/pull/19) 
Besides that I add **hoverColor** field for SidebarXTheme. To make hovering effect. 
 
https://user-images.githubusercontent.com/40857927/182709845-2e603a9d-037b-46c2-8bfb-e483163c95c7.mov

**Comment by Frezyx** [comment]
Now this functionality is available in [0.9.0 version of package](https://pub.dev/packages/sidebarx)
