### ISSUE TITLE
Pending pull request to add footer items

### ISSUE THREAD

**Issue by DavidCatalano** [Frezyx/sidebarx#29]
Per the contribution guidelines I am submitting this issue prior to actually making a pull request.

**Is your feature request related to a problem? Please describe.**
It would be nice to add footer items to the sidebar that are listed just above the expand icon

**Describe the solution you'd like**
I have a pending pull request with this functionality:
https://github.com/DavidCatalano/sidebarx

**Additional context** I've updated the version number in the README.md. The examples have footerItems added. 
![footerItem](https://user-images.githubusercontent.com/1626025/193708591-7349d318-df3d-493c-8bc2-97186e853dc2.gif)

**Comment by Frezyx** [comment]
Hello @DavidCatalano ✋🏻 
Cool feature !
I think it can be added !
