### ISSUE TITLE
Sidebar menu items not occupying the whole height available

### ISSUE THREAD

**Issue by melchorlapinigjr** [Frezyx/sidebarx#31]
**Describe the bug**
I noticed when I upgraded to sidebarx 0.13.0, the menu items are not occupying the whole height available in the view. 

**To Reproduce**
1. Upgrade to version 0.13.0 
2. Put 8 sidebar items
3. Run in Google Chrome

**Screen recording**
https://user-images.githubusercontent.com/40294247/194965229-665de925-13be-4bd3-80e9-a9a1b0997ed4.mp4

**Desktop (please complete the following information):**
 - Browser Google Chrome

**Comment by Frezyx** [comment]
Hello @melchorlapinigjr !
I see this bug. 

We need to add this line of code on 146 line to fix the situation.
```dart
if (widget.footerItems.isNotEmpty)
```

![telegram-cloud-photo-size-2-5343667369471492408-y](https://user-images.githubusercontent.com/40857927/194966335-20c3b129-1dba-4009-9d3e-1329924d4fa5.jpg)

**Comment by Frezyx** [comment]
I'am without notebook now. 
I will be able to release fixes only tomorrow 😢

**Comment by melchorlapinigjr** [comment]
@Frezyx No worries mate. Thanks for this quick work around. Cheers!

**Comment by Frezyx** [comment]
@melchorlapinigjr Hello you can check fix in [0.14.0 version ](https://pub.dev/packages/sidebarx)
