### ISSUE TITLE
Change GestureDetector to InkWell

### ISSUE THREAD

**Issue by hulohot** [Frezyx/sidebarx#37]
**Is your feature request related to a problem? Please describe.**
When developing an application for Flutter Web it is not clear to the user that the sidebar buttons are something they need to click on. I.E. their cursor does not change to the "finger pointing" icon, it remains the normal cursor. 

**Describe the solution you'd like**
This was a request from a client and I was able to easily implement this by changing the `GestureDetector` in the `SidebarXCell` class to an `InkWell`. I am not sure what other effects this has, but I don't see any issues with this solution. I'll make a PR for this feature request for you to approve if it makes sense, if not I'll just fork this repo :)

**Comment by Frezyx** [comment]
Hello @hulohot !
I think this will be a useful functionality. 
I will be waiting for your PR

**Comment by hulohot** [comment]
I had been using an older version of the package before the `MouseRegion` was added, it seems like my issue has already been fixed! I'll close this issue.
