### ISSUE TITLE
Icon As widget 

### ISSUE THREAD

**Issue by ali-taha-albaap** [Frezyx/sidebarx#5]
I need to use png icons but the SidebarXItem accepts only IconData

Please make the icon as a widget or add an item builder. or help me with a workaround 

please replay soon

**Comment by Frezyx** [comment]
Hello @ali-taha-albaap !
Thank you for this issue. I understand you. 
It is the necessary functionality

I'll be able to do it soon, ...or you can help me with it 
If it is urgent. I will accept your contribution

**Comment by Frezyx** [comment]
Hello @ali-taha-albaap !
I implement your feature request in 0.4.0 version of package

See changes in [CHANGELOG.md](https://github.com/Frezyx/sidebarx/blob/main/CHANGELOG.md)
or in updated [example](https://github.com/Frezyx/sidebarx/blob/main/example/lib/main.dart#:~:text=iconWidget%3A%20FlutterLogo()%2C)
