### ISSUE TITLE
The drawer to small and not expand

### ISSUE THREAD

**Issue by pujakhalika** [Frezyx/sidebarx#52]
After click app bar drawer is perfectly work but to small and not expand on label text

![bug](https://github.com/Frezyx/sidebarx/assets/73125355/45d48767-99a5-406a-aa48-d47b59582456)

Here my code : 
Controller : 
![controller](https://github.com/Frezyx/sidebarx/assets/73125355/87a8e5d9-9c0b-4e24-b6bf-b911f00b8e89)

Home Screen : 
![1](https://github.com/Frezyx/sidebarx/assets/73125355/b7947253-9aa6-49e9-935a-afec1ab4d813)

![2](https://github.com/Frezyx/sidebarx/assets/73125355/7ea34d85-19ba-410d-b1e1-9e968289fbd9)

Version : 

![version](https://github.com/Frezyx/sidebarx/assets/73125355/c1b50032-e7cd-4712-9ca8-ecb6ae48ae84)

**Comment by hedihadi** [comment]
same problem here, i cant use this package because of this
