### ISSUE TITLE
Default mode Extended.

### ISSUE THREAD

**Issue by zeeboydrummer** [Frezyx/sidebarx#7]
Thank you for such a wonderful SideBar to begin with. For Flutter Web, this is one of the best sidebars I have found.
One of the features that would be great for web is the ability to choose the default toggle style for the Sidebar. I am building a dashboard where it would be apt to load the sidebar in extended mode. I tried but could not find the option.

Please see if a toggle option could be added to select the default load mode.

Appreciate all your help.

**Comment by Frezyx** [comment]
Thank you for praising the library.
I don't fully understand you.
Can you give an example of what is needed ?

**Comment by maliksenpai** [comment]
`
SidebarX(
              controller: SidebarXController(selectedIndex: 0, extended: true),
              items: const [
                SidebarXItem(icon: Icons.home, label: 'Home'),
                SidebarXItem(icon: Icons.search, label: 'Search'),
              ],
            ),
`

If your controller extended in initstate, it will be extended when open page as in the example.
