### ISSUE TITLE
Sidebar preforms loading animation every time you navigate to a new route

### ISSUE THREAD

**Issue by hulohot** [Frezyx/sidebarx#8]
**Describe the bug**
I am using the [go router package](https://pub.dev/packages/go_router) to manage navigation in my app, where each page has its own route. Every time I navigate to a new route, whether via a sidebar button or any other method, the sidebar animates in the icon and text from the right to the left.

**To Reproduce**
See the video below

https://user-images.githubusercontent.com/38847800/176307506-61342a36-11f0-4145-9b0e-d7060a7759a8.mov

**Expected behavior**
I should be able to adjust the animation duration (in my case set it to 0)
`duration: const Duration(milliseconds: 300),`
See the code [here](https://github.com/Frezyx/sidebarx/blob/main/lib/src/sidebarx_base.dart#L50)

**Desktop (please complete the following information):**
 - OS: Mac OSX Big Sur 11.6
 - Browser: Chrome
 - Version: 102.0.5005.115

Thank you for any help with this issue, and if you have any questions about what I mean or would like me to just submit a PR that's fine as well. This is a great flutter package, thank you for making it 😃

**Comment by Frezyx** [comment]
Hello @hulohot !
You're right this looks like bug of package.
You can fix it via fork/pr or please wait when I have time to solve this problem
